### ISSUE TITLE
Labbar loopar

### ISSUE THREAD

**Issue by Conhan93** [Conhan93/JustC#5]

**Comment by Conhan93** [comment]
Needs to be commented

**Comment by Ahmedabbe** [comment]
Kolla line 83 och säg va du tycker om förklaringen där. För mycket? Inte korrekt? Annars är loop klar

**Comment by Ahmedabbe** [comment]
[https://i.kym-cdn.com/entries/icons/original/000/001/030/DButt.jpg](url)

**Comment by Conhan93** [comment]
Looks good! Think this file is done, closing issue
